(library
 (public_name semgrep.rml)
 (name semgrep_rml)
 (wrapped false)
 (libraries
  semgrep.il
  ast_generic
  base64
  commons
  yojson
  semgrep.tainting
  semgrep.core_scan
  ; for the LSP-style diagnostics renderer in Diagnostics_renderer.
  semgrep.core_runner
  semgrep.osemgrep_reporting
  parallelism
  logs.fmt
 ))
