(library
 (public_name semgrep.rml)
 (name semgrep_rml)
 (wrapped false)
 (libraries
  semgrep.il
  ast_generic
  commons
  yojson
  semgrep.tainting
  semgrep.core_scan
  ; for the LSP-style diagnostics renderer in Taint_serializer.
  semgrep.core_runner
  semgrep.osemgrep_reporting
  parallelism
  semgrep.memory_release
 ))
